name: membership-connector-app

services:
  postgres:
    image: postgres
    container_name: membership-connector-app-postgres
    environment:
      POSTGRES_DB: membership-connector-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - membership-connector-app_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  membership-connector-app_postgres_data:
